### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lskaka** [xD-E-A-T-Hx/Gmail_Bot#2]
DevTools listening on ws://127.0.0.1:64282/devtools/browser/d25cb77f-4695-4999-9c8b-b811461a8560
Created TensorFlow Lite XNNPACK delegate for CPU.
[6900:9800:0608/035116.423:ERROR:device_event_log_impl.cc(195)] [03:51:16.422] Bluetooth: bluetooth_adapter_winrt.cc:1056 Getting Default Adapter failed.

do you know how to fix this?

**Comment by xD-E-A-T-Hx** [comment]
Hey, I don’t see how any of that error is in connection with this script. Can you be more specific with it. Does it appear when you run it initially etc ?

**Comment by lskaka** [comment]
> Hey, I don’t see how any of that error is in connection with this script. Can you be more specific with it. Does it appear when you run it initially etc ?

DevTools listening on ws://127.0.0.1:57920/devtools/browser/c8e9fd07-ec03-4d19-bf7b-3c6a9c66d005
Traceback (most recent call last):
  File "G:\gmailcreator2\Gmail_Bot.py", line 219, in <module>
    driver.get(URL)
  File "C:\Users\Paulus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Paulus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Paulus\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=125.0.6422.142)
Stacktrace:
        GetHandleVerifier [0x00007FF79BBF1F52+60322]
        (No symbol) [0x00007FF79BB6CEC9]
        (No symbol) [0x00007FF79BA27EBA]
        (No symbol) [0x00007FF79BA1FEA2]
        (No symbol) [0x00007FF79BA109C4]
        (No symbol) [0x00007FF79BA12212]
        (No symbol) [0x00007FF79BA10CF1]
        (No symbol) [0x00007FF79BA104D1]
        (No symbol) [0x00007FF79BA10410]
        (No symbol) [0x00007FF79BA0E39D]
        (No symbol) [0x00007FF79BA0E9DC]
        (No symbol) [0x00007FF79BA2AC91]
        (No symbol) [0x00007FF79BABC5FE]
        (No symbol) [0x00007FF79BA9C21A]
        (No symbol) [0x00007FF79BABBC80]
        (No symbol) [0x00007FF79BA9BFC3]
        (No symbol) [0x00007FF79BA69617]
        (No symbol) [0x00007FF79BA6A211]
        GetHandleVerifier [0x00007FF79BF094AD+3301629]
        GetHandleVerifier [0x00007FF79BF536D3+3605283]
        GetHandleVerifier [0x00007FF79BF49450+3563680]
        GetHandleVerifier [0x00007FF79BCA4326+790390]
        (No symbol) [0x00007FF79BB7750F]
        (No symbol) [0x00007FF79BB73404]
        (No symbol) [0x00007FF79BB73592]
        (No symbol) [0x00007FF79BB62F9F]
        BaseThreadInitThunk [0x00007FFF4DF47344+20]
        RtlUserThreadStart [0x00007FFF4E3E26B1+33]

**Comment by xD-E-A-T-Hx** [comment]
What chromedriver are you using. Is it correct version for your browser ?

**Comment by xD-E-A-T-Hx** [comment]
Also check your proxies are valid as this can throw a tunnel error too

**Comment by lskaka** [comment]
> What chromedriver are you using. Is it correct version for your browser ?

i;m try reinstal my chrome know my chromedriver version : 
ChromeDriver 114.0.5735.90
Google Chrome Version 114.0.5735.199

**Comment by lskaka** [comment]
> Also check your proxies are valid as this can throw a tunnel error too

Attempt 1: Using FreeProxy library. Proxy: http://47.56.110.204:8989
Attempt 2: Using FreeProxy library. Proxy: http://20.111.54.16:8123
Attempt 3: Using FreeProxy library. Proxy: http://170.187.232.112:80
Attempt 4: Using FreeProxy library. Proxy: http://139.59.1.14:8080
Attempt 5: Using FreeProxy library. Proxy: http://20.111.54.16:8123
Attempt 6: Using FreeProxy library. Proxy: http://20.111.54.16:8123
Attempt 7: Using FreeProxy library. Proxy: http://47.56.110.204:8989
Attempt 8: Using FreeProxy library. Proxy: http://20.111.54.16:8123
Attempt 9: Using FreeProxy library. Proxy: http://20.111.54.16:8123
Attempt 10: Using FreeProxy library. Proxy: http://103.127.1.130:80
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15

i'm using paid proxies but always like that

**Comment by lskaka** [comment]
> Also check your proxies are valid as this can throw a tunnel error too

how to just using premium/paid proxy ?

**Comment by xD-E-A-T-Hx** [comment]
Try a simple script to make sure your driver works 


from selenium import webdriver
from selenium.common.exceptions import WebDriverException

# Initialize Chrome options
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--no-proxy-server')

try:
    # Initialize the Chrome driver with options
    driver = webdriver.Chrome(options=chrome_options)
    
    # Access the URL
    driver.get("https://www.google.com")
except WebDriverException as e:
    print(f"An error occurred: {e}")
finally:
    # Clean up
    driver.quit()
